[ga]
num_generations = 100
population_size = 20
mutation_rate = 0.05
crossover_rate = 0.8
num_trials = 100

[solver]
dt = 0.01
buffer_period = 2000
sampling_rate = 100


[model]
param_lower_bounds = [-1.0, 0.0, 0.2]
param_upper_bounds = [1.0, 5.0, 2.0]

